apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins-agent
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-volume
            mountPath: /Users/INE12398082/Desktop/Aniket/jenkins-k8s
      volumes:
        - name: jenkins-volume
          persistentVolumeClaim:
            claimName: jenkins-pv-claim