apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
  labels:
    purpose: jenkins-shared-deployement
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins-pv-claim
    namespace: jenkins
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "<your-local-path>"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - docker-desktop